fixtures:
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    provision: "git://github.com/puppetlabs/provision.git"
    puppet_agent: 
      repo: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.13.0
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  forge_modules:
    mount_core: "puppetlabs/mount_core"
  symlinks:
    lvm: "#{source_dir}"
